### ISSUE TITLE
Wrong output when the same refs in another place have another order

### ISSUE THREAD

**Issue by DmitrySharabin** [LeaVerou/eleventy-plugin-citations#5]
Suppose we have:

```
Correct: [@epstein_this_2023; @Kim2017]

Wrong: [@Kim2017; @epstein_this_2023]
```

It produces the following result (here `href`s are used as visual aids):

<img width="427" alt="SCR-20240721-kuxi" src="https://github.com/user-attachments/assets/56f6973c-aa44-4464-9eaa-1823bcef2544">

As we can see, in both cases, the output is the same `[1, 2]`. But in the second case, it's obviously wrong.

**Comment by DmitrySharabin** [comment]
Okay, here is what I could find. We get the correct citation text to render (from `citeproc-js`) when adding a citation. Then, we parse it and link its parts to the corresponding items in the bibliography _based on the order of the citations in the source code_. We do not consider, though, that a citation might already have a number associated with it (as it was already cited).

So, when adding links to the citation parts, we should check whether this part was already used (e.g., we already have an entry with number 2). If so, we should find out which ref (in `this.references`??) has this number. Then, we should find this ref in the `citations` array (the one we pass to the `cite()` method) and link the corresponding part to it.

**Comment by DmitrySharabin** [comment]
Interestingly, for citation sequences like `[a–b]`, everything works correctly regardless.

For example (based on the demo):

```
[@verou_mavo_2016; @verou_extending_2018; @zhang_wikum_2017]

[@chang_using_2016; @verou_mavo_2016; @zhang_wikum_2017; @verou_extending_2018]

[@bakke_expressive_2016; @bakke_spreadsheet-based_2011; @chang_using_2016; @chang_creating_2014]
```

Produces (correctly)

<img width="487" alt="image" src="https://github.com/user-attachments/assets/d76744d4-4382-4c4f-8019-21746f1702e4">

**Comment by LeaVerou** [comment]
So range citations go through a different (slower) code path. I wonder if it has to do with that.

**Comment by DmitrySharabin** [comment]
> So range citations go through a different (slower) code path. I wonder if it has to do with that.

It looks like it does. I checked: If we go the ”slower“ code path in all cases, we get the correct result.

**Comment by LeaVerou** [comment]
I'd rather we didn't, can we simply fix the detection so that it goes through the slow code path when needed?

**Comment by DmitrySharabin** [comment]
> I'd rather we didn't, can we simply fix the detection so that it goes through the slow code path when needed?

Unfortunately, I don't see how we can fix the detection. For example, `[1, 2]` can be correct in one case but incorrect in the others (see [the first comment](https://github.com/h-tex/eleventy-plugin-citations/issues/5#issue-2421327949)). The only case (it seems like the most common one) where we don't need the slow path is when we reference one source only.

**Comment by LeaVerou** [comment]
yeah, lets do that
